### ISSUE TITLE
structure d'origine de la protéine -- projet Barstar

### ISSUE THREAD

**Issue by WanyingBEI** [M1-BIBS-Python/Documents#2]
Bonjour,
J'ai vu que le fichier start_prot_only.pdb est ajouté, et le contenu de ce fichier est identique avec le model 0 du fichier md_prot_only_skip10.pdb et du fichier md_prot_only_skip100.pdb. Je voudrais donc savoir si vous attendez un script prenant le contenu de start_prot_only.pdb comme structure d'origine de la protéine ou si un script prenant directement le model 0 comme structure d'origine vous conviendrait aussi.
Cordialement.

**Comment by ArnaudFerre** [comment]
Bonjour,
Juste pour commencer : ce n'est pas dans ce répertoire (Documents) que l'on devait déclarer des "Issues" mais dans celui de ton projet... (d'où mon temps de réponse)
A présent, ce que tu as constaté est tout à fait normal : les fichiers dynamiques contiennent en effet aussi la structure d'origine parmi toutes les "photos" d'évolution structurelle de ta protéine. Après, on peut tout à fait imaginer que la structure d'origine ne soit pas forcément le "model 0", d'où l'utilité d'avoir un fichier statique (start_prot_only.pdb) pour être sûr de le reconnaître.
Bref, pour répondre à ta question : au fond, ça n'a pas grande importance.  
L'exo stipulait plutôt d'utiliser le fichier statique comme référence, mais tant que ce que tu as fait est bien expliqué, ça n'impactera pas ta note, car je n'ai pas d'attente strict à ce niveau.
